# Generated by Django 3.1.2 on 2020-10-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_antiga', '0002_registrousuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrousuarios',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
